### PR TITLE
Add delay to client.send_message()

### PR DESCRIPTION
**Pull request by GauthierPLM**
Add possibility to delay message sending (to make the bot more "natural").

### CODE REVIEW

**Comment by worblehat** [comment]
Good idea. Thank you!

**Comment by GauthierPLM** [comment]
Currently, if we keep that, the bot block during the sleep.

There is three solutions :
- fork the program and exit after message sent.
- don't sleep. Use a variable to stock the hour when the message should be sent.
- use threading.

Which one do you prefer ? I'll implement it.

**Comment by worblehat** [comment]
You are right, I've thought about that, too. My preferred solution would be, to use the [Task class](https://github.com/worblehat/FredIRC/blob/ab9874485ab703d8f3d3153ad28176c67e40e24f/fredirc/task.py) I wrote for situations like this.

You can pass a function that will be run later to its constructor. It should work like this:

``` python
def send():
    self._send_message(...)
task = Task(delay, False, send)
task.start()
```

The Task-class is just a thin wrapper around [asyncio's method for delayed calls](https://docs.python.org/3/library/asyncio-eventloop.html#delayed-calls).

**Comment by GauthierPLM** [comment]
I tried your Task class with the following code:

``` python
def send_message(self, channel, message, delay=0.0):
    task = Task(delay, False, self._send_message(
        messages.privmsg(channel, message, self._state.nick)))
    task.start()
```

but the message is sent directly, even if I delay it.

``` python
def handle_own_join(self, channel):
    self.client.send_message(channel, "Hello tout le monde ! :)", 5)
```

Edit :
Even the following call doesn't work :

``` python
    task = Task(10.5, False, self._send_message(
        messages.privmsg(channel, message, self._state.nick)))
```

**Comment by worblehat** [comment]
I don't know if you are familiar with local functions. You have to define one, that calls `_send_message()` and pass it to the `Task`:

``` python
def send_message(self, channel, message, delay=0.0):  
    def send():
        self._send_message(messages.privmsg(channel, message, self._state.nick))
    task = Task(delay, False, send)
    task.start()
```

It's important not to place the paranthesis `()` behind `send` when passing it to the Task. What you did in your code above was:
1. call `self._send_message()` immediately
2. and pass the return value to `Task`

What you actually want is to pass the function, so `Task` can execute it at the right time.
I hope that helps :)

**Comment by worblehat** [comment]
Two suggestions for the implementation:
1. Avoid the overhead of using `Task` when `delay` is `0.0` and call `self._send_message()` directly (like before)
2. Mention in the docstring that `send_message()` does not block when `delay > 0.0`

**Comment by GauthierPLM** [comment]
Aaah, okay ! Thanks for the explanation, I never used local functions before. ^^'
I'll correct the code and add your suggestions and push the result soon.

**Pull request merged**
